"""First migration

Revision ID: 0bff392e8f3d
Revises: 
Create Date: 2024-07-23 19:45:19.113070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bff392e8f3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vehicle_routes_id', table_name='vehicle_routes')
    op.drop_table('vehicle_routes')
    op.drop_index('ix_routes_id', table_name='routes')
    op.drop_table('routes')
    op.drop_index('ix_vehicles_id', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index('ix_vehicle_drivers_id', table_name='vehicle_drivers')
    op.drop_table('vehicle_drivers')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_locations_id', table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_maintenances_id', table_name='maintenances')
    op.drop_table('maintenances')
    op.drop_index('ix_remittances_id', table_name='remittances')
    op.drop_table('remittances')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remittances',
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_remittances_id', 'remittances', ['id'], unique=False)
    op.create_table('maintenances',
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maintenances_id', 'maintenances', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_locations_id', 'locations', ['id'], unique=False)
    op.create_table('users',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=100), nullable=False),
    sa.Column('role', sa.VARCHAR(length=7), nullable=False),
    sa.Column('id_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('dob', sa.DATE(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('driving_license_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id_number')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_table('vehicle_drivers',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_drivers_id', 'vehicle_drivers', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.Column('plate_number', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('engine_capacity', sa.VARCHAR(length=20), nullable=False),
    sa.Column('buying_value', sa.FLOAT(), nullable=False),
    sa.Column('projected_return_per_day', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_index('ix_vehicles_id', 'vehicles', ['id'], unique=False)
    op.create_table('routes',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routes_id', 'routes', ['id'], unique=False)
    op.create_table('vehicle_routes',
    sa.Column('vehicle_id', sa.INTEGER(), nullable=True),
    sa.Column('route_id', sa.INTEGER(), nullable=True),
    sa.Column('date_assigned', sa.DATE(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vehicle_routes_id', 'vehicle_routes', ['id'], unique=False)
    # ### end Alembic commands ###
